steps:
- name: 'gcr.io/qwiklabs-gcp-01-d5da1fdd9b68 /docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-01-d5da1fdd9b68 /dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s
options:
  pool:
    name: 'projects/qwiklabs-gcp-01-d5da1fdd9b68 /locations/asia-northeast1/workerPools/3' 
